// Turn the index title into SVG outlines, one path per letter, so it can be drawn on with a pen.
// Geist Medium (500), kerned, tracked like .wordmark-xl (-0.045em). Output: src/lib/titlePaths.ts
// Run: node scripts/build-title.mjs [text]
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import opentype from "opentype.js";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const require = createRequire(import.meta.url);
const text = process.argv[2] ?? "in.between";
const fontFile = require.resolve("@fontsource/geist/files/geist-latin-500-normal.woff");
const buf = readFileSync(fontFile);
const font = opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));

const EM = 1000;
const scale = EM / font.unitsPerEm;
const tracking = -0.045 * EM;
const ascender = Math.round(font.ascender * scale);
const descender = Math.round(font.descender * scale);

const glyphs = font.stringToGlyphs(text);
let x = 0;
const letters = glyphs.map((g, i) => {
  const path = g.getPath(x, 0, EM);
  const d = path.toPathData(1);
  const box = path.getBoundingBox();
  const letter = { ch: text[i], d, x: Math.round(x), x1: Math.round(box.x1), x2: Math.round(box.x2), y1: Math.round(box.y1), y2: Math.round(box.y2) };
  const kern = i < glyphs.length - 1 ? font.getKerningValue(g, glyphs[i + 1]) * scale : 0;
  x += g.advanceWidth * scale + kern + tracking;
  return letter;
});
const width = Math.round(x - tracking);
const top = Math.min(...letters.map((l) => l.y1));
const bottom = Math.max(...letters.map((l) => l.y2));

const out = `// Generated by scripts/build-title.mjs from Geist Medium. Do not edit.
// Units: 1000 per em; y runs from -ascender (top) to -descender (bottom), baseline at 0.
export const title = ${JSON.stringify({ text, em: EM, ascender, descender, width, top, bottom, letters })} as const;
`;
writeFileSync(resolve(root, "src/lib/titlePaths.ts"), out);
console.log(`title: ${letters.length} letters, ${width} units wide → src/lib/titlePaths.ts`);
